# This is a basic workflow to help you get started with Actions
name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/30 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"
        echo "Holaa" 
